# Generated by Django 6.0.5 on 2026-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                default=6093433909, max_length=10, verbose_name="id телеграм чата"
            ),
            preserve_default=False,
        ),
    ]
