# Generated by Django 6.0.5 on 2026-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="id телеграм чата"
            ),
        ),
    ]
