# Generated by Django 6.0.5 on 2026-05-25 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Место выполнения привычки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Место выполнения привычки",
                "verbose_name_plural": "Места выполнения привычек",
            },
        ),
        migrations.CreateModel(
            name="UsefulHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_for_habit",
                    models.DateTimeField(verbose_name="Время для выполнения привычки"),
                ),
                ("action", models.CharField(max_length=250, verbose_name="Действие")),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Привычку нельзя выполнять чаще, чем раз в день"
                            ),
                            django.core.validators.MaxValueValidator(
                                7,
                                message="Привычку можно выполнять не реже, чем раз в 7 дней",
                            ),
                        ],
                        verbose_name="Переодичность выполнения для напоминания в днях",
                    ),
                ),
                (
                    "text_reward",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "lead_time",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Время выполнения не может быть меньше секунды"
                            ),
                            django.core.validators.MaxValueValidator(
                                120, "Время выполнения не может быть больше 120 секунды"
                            ),
                        ],
                        verbose_name="Время выполнения в секундах",
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="Признак публичности")),
            ],
        ),
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_for_habit",
                    models.DateTimeField(verbose_name="Время для выполнения привычки"),
                ),
                ("action", models.CharField(max_length=250, verbose_name="Действие")),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Привычку нельзя выполнять чаще, чем раз в день"
                            ),
                            django.core.validators.MaxValueValidator(
                                7,
                                message="Привычку можно выполнять не реже, чем раз в 7 дней",
                            ),
                        ],
                        verbose_name="Переодичность выполнения для напоминания в днях",
                    ),
                ),
                (
                    "lead_time",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Время выполнения не может быть меньше секунды"
                            ),
                            django.core.validators.MaxValueValidator(
                                120, "Время выполнения не может быть больше 120 секунды"
                            ),
                        ],
                        verbose_name="Время выполнения в секундах",
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="Признак публичности")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pleasant_habits_at_this_place",
                        to="habits.place",
                        verbose_name="Место выполнения привычки",
                    ),
                ),
            ],
        ),
    ]
