# Generated by Django 6.0.5 on 2026-05-25 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pleasanthabit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pleasant_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель привычки",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userful_habits_at_this_place",
                to="habits.place",
                verbose_name="Место выполнения привычки",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="pleasant_habit_reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_userful_habits",
                to="habits.pleasanthabit",
                verbose_name="Приятная привычка в награду",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userful_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель привычки",
            ),
        ),
    ]
