# Generated by Django 6.0.5 on 2026-05-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pleasanthabit",
            name="time_for_habit",
            field=models.TimeField(verbose_name="Время для выполнения привычки"),
        ),
        migrations.AlterField(
            model_name="usefulhabit",
            name="time_for_habit",
            field=models.TimeField(verbose_name="Время для выполнения привычки"),
        ),
    ]
