# Generated by Django 6.0.5 on 2026-05-29 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0005_alter_place_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="usefulhabit",
            name="last_notification",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата последнего напоминания",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="next_notification",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата следующего напоминания"
            ),
        ),
    ]
